SELECT 
	PC.CATEGORYTYPE,
	COUNT(U.ID) AS VOLS,
	SUM(DATEDIFF(HH,T.CLOCKINTIME,T.CLOCKOUTTIME)) AS HRS
FROM
	TIMESHEET T
	LEFT JOIN PROJECT P ON T.PROJECT_ID = P.Id
	LEFT JOIN PROJECTCATEGORY PC ON P.CATEGORYID = PC.ID
	LEFT JOIN dbo.[User] U ON T.[USER_ID] = U.ID
WHERE 
	T.CLOCKINTIME BETWEEN '20170101' AND '20171201'
GROUP BY
	PC.CATEGORYTYPE;

SELECT 
	COUNT(U.ID) AS STUDENTS
FROM
	TIMESHEET T
	LEFT JOIN PROJECT P ON T.PROJECT_ID = P.Id
	LEFT JOIN PROJECTCATEGORY PC ON P.CATEGORYID = PC.ID
	LEFT JOIN dbo.[User] U ON T.[USER_ID] = U.ID
WHERE 
	P.CATEGORYID = 1
	AND
	T.CLOCKINTIME BETWEEN '20170101' AND '20171201'
	AND
	U.COLLEGESTATUS = 2;