SELECT 
	PC.CATEGORYTYPE AS category,													
	COUNT(U.ID) AS numVolunteers,													
	SUM(DATEDIFF(HH,T.CLOCKINTIME,T.CLOCKOUTTIME)) AS numHours,					
	SUM(CASE WHEN U.COLLEGESTATUS = 3 THEN 1 ELSE 0 END) AS numStudents,			
	SUM(CASE WHEN U.VETERANSTATUS = 3 THEN 1 ELSE 0 END) AS numVeterans,			
	SUM(CASE WHEN U.DISABLEDSTATUS = 3 THEN 1 ELSE 0 END) AS numDisabled,			
	SUM(CASE WHEN U.INCOMEID = 2 THEN 1 ELSE 0 END) AS numUnder25k,				
	SUM(CASE WHEN U.ETHNICITYID = 2 THEN 1 ELSE 0 END) AS numNative,				
	SUM(CASE WHEN U.ETHNICITYID = 3 THEN 1 ELSE 0 END) AS numAsian,				
	SUM(CASE WHEN U.ETHNICITYID = 4 THEN 1 ELSE 0 END) AS numBlack,				
	SUM(CASE WHEN U.ETHNICITYID = 5 THEN 1 ELSE 0 END) AS numHispanic,			
	SUM(CASE WHEN U.ETHNICITYID = 6 THEN 1 ELSE 0 END) AS numHawaiian,			
	SUM(CASE WHEN U.ETHNICITYID = 7 THEN 1 ELSE 0 END) AS numWhite,				
	SUM(CASE WHEN U.ETHNICITYID = 8 THEN 1 ELSE 0 END) AS numTwoEthnic,			
	SUM(CASE WHEN U.gender = 'M' THEN 1 ELSE 0 END) AS male,						
	SUM(CASE WHEN U.gender = 'F' THEN 1 ELSE 0 END) AS female						
FROM
	TIMESHEET T
	LEFT JOIN PROJECT P ON T.PROJECT_ID = P.Id
	LEFT JOIN PROJECTCATEGORY PC ON P.CATEGORYID = PC.ID
	LEFT JOIN dbo.[User] U ON T.[USER_ID] = U.ID
WHERE 
	T.CLOCKINTIME BETWEEN '20170101' AND '20171201'
GROUP BY
	PC.CATEGORYTYPE;